package com.datapulse.logging;

public enum LogEventType {
    USER_LOGIN,
    USER_LOGOUT,
    USER_REGISTER,
    ORDER_PLACED,
    ORDER_STATUS_CHANGED,
    PRODUCT_VIEWED,
    AUTH_FAILED,
    AUTH_UNAUTHORIZED,
    API_REQUEST,
    CHAT_QUERY,
    CHATBOT_SQL_EXEC,
    CHATBOT_SQL_REJECTED,
    DATA_LOADED,
    ERROR_OCCURRED,
    USER_STATUS_CHANGED,
    STORE_STATUS_CHANGED,
    EMAIL_VERIFICATION_SENT,
    EMAIL_VERIFIED,
    SECURITY_ACCESS_DENIED,
    SECURITY_INVALID_TOKEN,
    SECURITY_XSS_ATTEMPT,
    SECURITY_SQLI_ATTEMPT,
    SECURITY_PRIVILEGE_ESCALATION
}
