ALTER TABLE stores ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE stores ADD COLUMN IF NOT EXISTS address VARCHAR(500);
ALTER TABLE stores ADD COLUMN IF NOT EXISTS city VARCHAR(100);
ALTER TABLE stores ADD COLUMN IF NOT EXISTS phone VARCHAR(30);
ALTER TABLE stores ADD COLUMN IF NOT EXISTS logo_url VARCHAR(1024);
