UPDATE categories SET name = 'Electronics'              WHERE id = 'cat00001';
UPDATE categories SET name = 'Clothing'                 WHERE id = 'cat00002';
UPDATE categories SET name = 'Shoes'                    WHERE id = 'cat00003';
UPDATE categories SET name = 'Home & Living'            WHERE id = 'cat00004';
UPDATE categories SET name = 'Jewelry & Accessories'    WHERE id = 'cat00005';
UPDATE categories SET name = 'Beauty & Care'            WHERE id = 'cat00006';
UPDATE categories SET name = 'Sports & Outdoor'         WHERE id = 'cat00007';
UPDATE categories SET name = 'Kitchen & Dining'         WHERE id = 'cat00008';
UPDATE categories SET name = 'Toys & Hobbies'           WHERE id = 'cat00009';
UPDATE categories SET name = 'Automotive'               WHERE id = 'cat00010';
UPDATE categories SET name = 'Baby & Kids'              WHERE id = 'cat00011';
UPDATE categories SET name = 'Computers & Technology'   WHERE id = 'cat00012';
UPDATE categories SET name = 'Furniture'                WHERE id = 'cat00013';
UPDATE categories SET name = 'Watches'                  WHERE id = 'cat00014';
UPDATE categories SET name = 'Bags & Wallets'           WHERE id = 'cat00015';
UPDATE categories SET name = 'Stationery'               WHERE id = 'cat00016';
UPDATE categories SET name = 'Health'                   WHERE id = 'cat00017';
UPDATE categories SET name = 'Pet Supplies'             WHERE id = 'cat00018';
UPDATE categories SET name = 'Home Improvement'         WHERE id = 'cat00019';
UPDATE categories SET name = 'Books & Media'            WHERE id = 'cat00020';
